### PR TITLE
Remove intermittently failing test

### PR DESCRIPTION
**Pull request by jamiebramwell**
The quasi-static component test is intermittently failing on LC. As this is the legacy physics module, it is not worth investigating as it will be deprecated soon.

See https://github.com/LLNL/serac/issues/668

### CODE REVIEW

**Comment by white238** [comment]
Sure you wouldn't rather just comment it out?

**Comment by jamiebramwell** [comment]
I honestly wasn't sure if ATS would bork at an empty ats file.

**Review by white238 — APPROVED** [review]

**Review by chapman39 — APPROVED** [review]
did you still want this merged?

**Comment by jamiebramwell** [comment]
Ahhh yes. This might be the cause of our weird CI failures.

**Pull request merged**
