### PR TITLE
Rebaseline tests and remove those that need to be fixed

### PR DESCRIPTION
**Pull request by chapman39**
Once https://github.com/LLNL/serac_tests/pull/18 is merged, the heat transfer changes will go away from this PR's diff

### CODE REVIEW

**Review by white238 — APPROVED** [review]

**Comment by btalamini** [comment]
Question: are these results already within the old tolerances?

**Comment by white238** [comment]
> Question: are these results already within the old tolerances?

That's a good question.. It shouldn't be hard to do a search and replace for the field names and see if they pass.

**Comment by chapman39** [comment]
I tested the old tolerances by doing the following:

* serac: checked out my integration tests pr https://github.com/LLNL/serac/pull/1067
* serac_tests: checked out to the current serac_tests on develop https://github.com/LLNL/serac_tests/tree/52028ec9c912418b2952b9d8ce6c7801ab6ec64c

```
cd <serac_repo>/tests/integration
find . -type f -name *.json | xargs sed -i 's/temperature/serac_temperature/g'
find . -type f -name *.json | xargs sed -i 's/velocity/serac_velocity/g'
find . -type f -name *.json | xargs sed -i 's/adjoint_displacement/serac_acceleration/g'
find . -type f -name *.json | xargs sed -i 's/displacement/serac_displacement/g'
```

EDIT: I realize now adjoint displacement should not be replaced by serac acceleration

* create a new serac build
* make -j
* salloc -N2 -Aeng --exclusive -t30 -ppbatch ats.sh

This was the result:
```
ATS SUMMARY April 17, 2024 17:59:46
FAILED:  24
tolerance_test(dyn_direct_solve_serial),
tolerance_test(dyn_direct_solve_parallel),
tolerance_test(dyn_solve_serial),
tolerance_test(dyn_solve_parallel),
serac(qs_direct_solve_serial),
serac(qs_direct_solve_parallel),
serac(qs_linear_serial),
serac(qs_linear_parallel), 
serac(qs_solve_serial),
serac(qs_solve_parallel),
serac(thermal_expansion_serial),
serac(thermal_expansion_parallel),
tolerance_test(dyn_exp_solve_serial),
tolerance_test(dyn_exp_solve_parallel),
tolerance_test(dyn_imp_solve_serial),
tolerance_test(dyn_imp_solve_parallel),
tolerance_test(dyn_imp_solve_restart_serial),
tolerance_test(dyn_imp_solve_restart_parallel),
tolerance_test(dyn_imp_solve_time_varying_serial),
tolerance_test(dyn_imp_solve_time_varying_parallel),
serac(static_reaction_exact_serial),
serac(static_reaction_exact_parallel),
tolerance_test(static_solve_serial), 
tolerance_test(static_solve_parallel)
PASSED:   34
SKIPPED:  10
```

Some of the tests are supposed to be commented out, so really these are the ones that fail:
- dyn_direct_solve
- dyn_solve
- dyn_exp_solve
- dyn_imp_solve
- dyn_imp_solve_restart
- dyn_imp_solve_time_varying
- static_solve

Some notes:
* `adjoint_displacement` is no longer a part of the tolerance files.
* `serac_temperature_rate` and `serac_acceleration` appear to be new and therefore cannot be tested.

**Comment by chapman39** [comment]
Closing in favor of this new PR: https://github.com/LLNL/serac_tests/pull/21

It was easier for me to start fresh, since I'm now using the old baselines and changing these as needed - rather than rebaselining everything.

**Pull request closed without merging**
